[package]
name = "music-module"
version = "0.1.0"
edition = "2024"

[dependencies]
minreq = { version = "2.14.1", features=["json-using-serde", "https"]  }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = {version = "0.4.42"}
