[workspace]
members = [
    "crates/search-engine",
]

[package]
name = "guslee"
version = "0.1.0"
edition = "2024"

[dependencies]
search-engine = {path = "crates/search-engine"}
actix-files = "0.6.7"
actix-web = "4.11.0"
markdown = "1.0.0"
simple_logger = "5.0"
log = "0.4"
