[package]
name = "search-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tantivy = "0.25.0"
tantivy-fst = "0.5.0"
tempdir = "0.3.7"
walkdir = "2.5.0"
serde = { version = "1.0", features = ["derive"] }
lru = "0.16.0"
